name: license-check
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.3"
      - name: Install license-header-checker
        run: ./install.sh
      - name: Run license check
        run: license-header-checker -a -r ./license_header.txt . go && [[ -z `git status -s` ]]
