name: Lint
on: [push]
jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.3"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
