name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21.3"
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Test end to end
        run: make test-e2e
